-- 268_persona_ageb_assign.sql
-- Task 4a.2 — owner-run UPDATE for simulation_personas AGEB fields.
-- Generated by scripts/geo/assign-persona-agebs.ts
-- run_id: 22de7536-3db5-4319-b69b-59137e4b972f
--
-- Touches ONLY: ageb_code, centroid_lat, centroid_lng, ageb_assignment_method
-- Requires migration 268_persona_ageb_assignment_method.sql first.
-- Idempotent: re-running sets the same values for the same persona ids.
-- Never touches prediction_markets / market_votes / real vote tables.

begin;

update simulation_personas set
  ageb_code = '0901600010054',
  centroid_lat = 19.460142,
  centroid_lng = -99.188807,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '010cbf28-86b4-488c-a90b-175b9117a611'::uuid;

update simulation_personas set
  ageb_code = '0901500011318',
  centroid_lat = 19.411637,
  centroid_lng = -99.176286,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '02b51dd0-b4d0-4428-96ea-5bfebd6ba4dd'::uuid;

update simulation_personas set
  ageb_code = '0901500011182',
  centroid_lat = 19.416554,
  centroid_lng = -99.173052,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '03bf61bb-febc-47d9-a16c-115bdc948f60'::uuid;

update simulation_personas set
  ageb_code = '0901600010158',
  centroid_lat = 19.456886,
  centroid_lng = -99.187797,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '03c2eecc-d1fd-4560-ada6-51d049139fe9'::uuid;

update simulation_personas set
  ageb_code = '090150001113A',
  centroid_lat = 19.416864,
  centroid_lng = -99.146608,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '0822e27b-c7a2-43f3-9f0c-e16849424cce'::uuid;

update simulation_personas set
  ageb_code = '0901500011549',
  centroid_lat = 19.42112,
  centroid_lng = -99.15242,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '08df5b3d-aaf8-43ba-89f8-1f6847e8d59d'::uuid;

update simulation_personas set
  ageb_code = '0901500011318',
  centroid_lat = 19.41135,
  centroid_lng = -99.176176,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '0b9bc6ee-cb99-4882-bfbe-27674534766c'::uuid;

update simulation_personas set
  ageb_code = '0901500010184',
  centroid_lat = 19.457157,
  centroid_lng = -99.151913,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '0caed288-d975-41b0-a097-7c58582eaa41'::uuid;

update simulation_personas set
  ageb_code = '0901600010143',
  centroid_lat = 19.454978,
  centroid_lng = -99.192934,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '0f787c0e-1333-40bb-8aa0-808d3b04c927'::uuid;

update simulation_personas set
  ageb_code = '0901500010589',
  centroid_lat = 19.440246,
  centroid_lng = -99.125247,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '0fe51b43-25a6-4b85-9ccb-938be299c9c9'::uuid;

update simulation_personas set
  ageb_code = '0901500010678',
  centroid_lat = 19.439193,
  centroid_lng = -99.165664,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '104f774f-69be-4b5a-a7fd-442a543a2bc8'::uuid;

update simulation_personas set
  ageb_code = '0901500010875',
  centroid_lat = 19.428742,
  centroid_lng = -99.145376,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '145a052c-1b94-44a4-bf52-e08b0b77eae1'::uuid;

update simulation_personas set
  ageb_code = '0901500010856',
  centroid_lat = 19.429083,
  centroid_lng = -99.154627,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '14850982-416b-4160-8f13-34e9ddd96fd7'::uuid;

update simulation_personas set
  ageb_code = '0901600010745',
  centroid_lat = 19.43033,
  centroid_lng = -99.202094,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '169d3d63-e2d7-4d87-a981-f4754c8abe45'::uuid;

update simulation_personas set
  ageb_code = '0901600010139',
  centroid_lat = 19.456962,
  centroid_lng = -99.19497,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '17e0489e-ac16-40c4-b77b-11eddebef453'::uuid;

update simulation_personas set
  ageb_code = '0901600010143',
  centroid_lat = 19.455358,
  centroid_lng = -99.192954,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '18515a15-d2c0-4535-91ff-928231786a31'::uuid;

update simulation_personas set
  ageb_code = '0901600011029',
  centroid_lat = 19.411643,
  centroid_lng = -99.18489,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '1976e109-0034-4567-a785-c717b6fdf855'::uuid;

update simulation_personas set
  ageb_code = '0901600010444',
  centroid_lat = 19.441932,
  centroid_lng = -99.203817,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '1af3c2e5-5aeb-464e-87fe-7da422d26db6'::uuid;

update simulation_personas set
  ageb_code = '0901600010143',
  centroid_lat = 19.455103,
  centroid_lng = -99.192849,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '1b6ca2f6-0128-4b47-8aa4-6580665062aa'::uuid;

update simulation_personas set
  ageb_code = '090150001113A',
  centroid_lat = 19.416799,
  centroid_lng = -99.146648,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '1c106c1a-1595-4816-a8a6-e5ad63a8fb8c'::uuid;

update simulation_personas set
  ageb_code = '090150001113A',
  centroid_lat = 19.416322,
  centroid_lng = -99.146621,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '1f8a5ee9-c587-40e6-806d-28bf65445993'::uuid;

update simulation_personas set
  ageb_code = '0901500011125',
  centroid_lat = 19.416403,
  centroid_lng = -99.151993,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '1fa0e082-9b35-4e65-9256-28c5cb34db7d'::uuid;

update simulation_personas set
  ageb_code = '0901500011483',
  centroid_lat = 19.405762,
  centroid_lng = -99.147738,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '20acdd2c-615a-46c7-9095-740875d12c70'::uuid;

update simulation_personas set
  ageb_code = '0901500011125',
  centroid_lat = 19.415916,
  centroid_lng = -99.152029,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '22dda38a-99a8-44a6-b2a2-507c106b6505'::uuid;

update simulation_personas set
  ageb_code = '0901600010603',
  centroid_lat = 19.435486,
  centroid_lng = -99.174403,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '277ca9cd-0409-4f99-a913-c8d0316471fd'::uuid;

update simulation_personas set
  ageb_code = '0901500011036',
  centroid_lat = 19.421815,
  centroid_lng = -99.146058,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '27d99059-6823-4343-ab7d-f5056d39cd39'::uuid;

update simulation_personas set
  ageb_code = '0901500010358',
  centroid_lat = 19.447633,
  centroid_lng = -99.126881,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '2ca719f9-5f91-425c-ab3b-938c1fe7544e'::uuid;

update simulation_personas set
  ageb_code = '0901500011089',
  centroid_lat = 19.420009,
  centroid_lng = -99.17388,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '2ccc121f-f298-4dc2-b5d6-8b2d24dad280'::uuid;

update simulation_personas set
  ageb_code = '0901500011229',
  centroid_lat = 19.408653,
  centroid_lng = -99.153134,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '2dad7ecb-4c4e-47e8-92e9-d4574b9791a6'::uuid;

update simulation_personas set
  ageb_code = '0901600010444',
  centroid_lat = 19.442087,
  centroid_lng = -99.204177,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '2e5348c2-380d-4425-8f92-0a7606634096'::uuid;

update simulation_personas set
  ageb_code = '0901500011303',
  centroid_lat = 19.412664,
  centroid_lng = -99.179457,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '2ff926fd-6197-49c4-a470-a5fb1ef59366'::uuid;

update simulation_personas set
  ageb_code = '0901500010466',
  centroid_lat = 19.451925,
  centroid_lng = -99.16037,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '352cbf6b-2c15-46f7-92dd-3eea10ce3c44'::uuid;

update simulation_personas set
  ageb_code = '0901500011182',
  centroid_lat = 19.41608,
  centroid_lng = -99.1731,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '35e434b8-ea50-4209-b131-665e00fa6d24'::uuid;

update simulation_personas set
  ageb_code = '0901600010660',
  centroid_lat = 19.434431,
  centroid_lng = -99.188846,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '360a5eae-8737-45b6-8ee1-d3fbf47a1aa7'::uuid;

update simulation_personas set
  ageb_code = '0901500011214',
  centroid_lat = 19.414179,
  centroid_lng = -99.162267,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '3783d8e5-116d-437a-85fb-bf728b78a469'::uuid;

update simulation_personas set
  ageb_code = '0901500011144',
  centroid_lat = 19.416223,
  centroid_lng = -99.140992,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '3a1878ed-655b-442a-93f8-aa9d98939351'::uuid;

update simulation_personas set
  ageb_code = '090150001113A',
  centroid_lat = 19.416876,
  centroid_lng = -99.146487,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '3c1f1ade-663f-4aff-a0bf-a6c0aa707622'::uuid;

update simulation_personas set
  ageb_code = '0901500011214',
  centroid_lat = 19.413592,
  centroid_lng = -99.16196,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '3c71d83b-6d44-483b-809d-ca063969be26'::uuid;

update simulation_personas set
  ageb_code = '0901500011110',
  centroid_lat = 19.415407,
  centroid_lng = -99.157035,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '3e080c61-269c-4e90-a128-28329b277fea'::uuid;

update simulation_personas set
  ageb_code = '0901500011125',
  centroid_lat = 19.416387,
  centroid_lng = -99.151878,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '40716ff6-ae2f-45df-9d5b-0f4f6a39a7ac'::uuid;

update simulation_personas set
  ageb_code = '0901600010675',
  centroid_lat = 19.434328,
  centroid_lng = -99.186155,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '408e4973-8d61-4fb3-8e58-49b70c0020ab'::uuid;

update simulation_personas set
  ageb_code = '0901600010675',
  centroid_lat = 19.43427,
  centroid_lng = -99.186316,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '432aef30-68b4-4eff-868b-8b4d4863245a'::uuid;

update simulation_personas set
  ageb_code = '0901500011089',
  centroid_lat = 19.419788,
  centroid_lng = -99.173789,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '43e5eeae-b0e3-4b8c-bd0a-2106c7c94ad8'::uuid;

update simulation_personas set
  ageb_code = '0901500011375',
  centroid_lat = 19.409236,
  centroid_lng = -99.160984,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '4473e59d-6b76-4b6e-8329-a82bd8215e4b'::uuid;

update simulation_personas set
  ageb_code = '0901500011106',
  centroid_lat = 19.41658,
  centroid_lng = -99.161907,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '46b48204-b678-4133-8ea2-533c17d33e5e'::uuid;

update simulation_personas set
  ageb_code = '0901500011125',
  centroid_lat = 19.416054,
  centroid_lng = -99.152185,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '476a73ac-9fbf-4664-9d95-0492309d5b33'::uuid;

update simulation_personas set
  ageb_code = '0901500010875',
  centroid_lat = 19.428785,
  centroid_lng = -99.145524,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '4924766a-b172-46c7-ae39-ce1a0a195275'::uuid;

update simulation_personas set
  ageb_code = '0901600010054',
  centroid_lat = 19.460062,
  centroid_lng = -99.188842,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '495eab1e-30ba-45b5-9765-e2c0930eeb2f'::uuid;

update simulation_personas set
  ageb_code = '0901500011214',
  centroid_lat = 19.413892,
  centroid_lng = -99.162516,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '49f49d03-7fd9-4046-9850-5ba8bce7f36f'::uuid;

update simulation_personas set
  ageb_code = '0901500010042',
  centroid_lat = 19.459243,
  centroid_lng = -99.157898,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '4b76e86b-8f52-4e19-a84f-e1313aec69c8'::uuid;

update simulation_personas set
  ageb_code = '090150001120A',
  centroid_lat = 19.414179,
  centroid_lng = -99.167571,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '4d7c095a-97ce-4879-8ffd-f15788e9e4c4'::uuid;

update simulation_personas set
  ageb_code = '0901500011233',
  centroid_lat = 19.411902,
  centroid_lng = -99.147292,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '5032c35c-2f90-4799-9842-195d2882782b'::uuid;

update simulation_personas set
  ageb_code = '0901600010783',
  centroid_lat = 19.428749,
  centroid_lng = -99.187941,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '5064a852-d2af-4519-9f33-db92dbc66ba2'::uuid;

update simulation_personas set
  ageb_code = '0901500010343',
  centroid_lat = 19.447858,
  centroid_lng = -99.128926,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '51ecd97f-b4a4-4b5a-8cdd-3575cae5620a'::uuid;

update simulation_personas set
  ageb_code = '0901500011341',
  centroid_lat = 19.409203,
  centroid_lng = -99.16992,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '52755f81-f930-475b-a94f-ebadeb667fd5'::uuid;

update simulation_personas set
  ageb_code = '0901500011233',
  centroid_lat = 19.412113,
  centroid_lng = -99.147197,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '52c4fdc2-cc27-4c9c-a805-c628f9ff1aa9'::uuid;

update simulation_personas set
  ageb_code = '0901500011233',
  centroid_lat = 19.412181,
  centroid_lng = -99.147562,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '54b3d3ce-455a-4af2-872f-85e2069b0737'::uuid;

update simulation_personas set
  ageb_code = '0901600010571',
  centroid_lat = 19.44043,
  centroid_lng = -99.191839,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '55284a8a-bfc2-4d24-8010-5a54a1e664f1'::uuid;

update simulation_personas set
  ageb_code = '0901500011233',
  centroid_lat = 19.411931,
  centroid_lng = -99.14728,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '55857cd6-17ea-4867-b904-85f8435696ab'::uuid;

update simulation_personas set
  ageb_code = '0901500011144',
  centroid_lat = 19.416034,
  centroid_lng = -99.141141,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '574a6e98-e3a0-4002-82dd-b28634a7e81e'::uuid;

update simulation_personas set
  ageb_code = '0901600010054',
  centroid_lat = 19.460257,
  centroid_lng = -99.188508,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '5cbc7e57-1b88-4e13-992b-f96981593218'::uuid;

update simulation_personas set
  ageb_code = '0901500011089',
  centroid_lat = 19.419892,
  centroid_lng = -99.174179,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '5f86fb1d-f622-442c-a4e8-85ab80586f06'::uuid;

update simulation_personas set
  ageb_code = '0901500011017',
  centroid_lat = 19.422165,
  centroid_lng = -99.156437,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '6315b4a3-b386-4f11-a554-6178d66f33b2'::uuid;

update simulation_personas set
  ageb_code = '0901500010606',
  centroid_lat = 19.442416,
  centroid_lng = -99.156851,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '64aeed2c-98fa-470d-8394-ae2142809080'::uuid;

update simulation_personas set
  ageb_code = '0901500010343',
  centroid_lat = 19.448182,
  centroid_lng = -99.128659,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '65eb68f2-5627-4ae4-90db-a53e661e71d4'::uuid;

update simulation_personas set
  ageb_code = '0901500010184',
  centroid_lat = 19.456785,
  centroid_lng = -99.151702,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '6898d5c2-84fa-4029-99b0-e16b1a9c78f3'::uuid;

update simulation_personas set
  ageb_code = '0901500011089',
  centroid_lat = 19.419877,
  centroid_lng = -99.174165,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '6c5bda1f-eca2-48a9-8db7-7dbbecb40c1a'::uuid;

update simulation_personas set
  ageb_code = '0901600010158',
  centroid_lat = 19.456927,
  centroid_lng = -99.188408,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '6de63df0-7520-4f28-8645-876af8fa85dc'::uuid;

update simulation_personas set
  ageb_code = '0901500011411',
  centroid_lat = 19.408469,
  centroid_lng = -99.179994,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '6efef3e1-8df5-44cd-b239-e3472a0ad726'::uuid;

update simulation_personas set
  ageb_code = '0901600010463',
  centroid_lat = 19.443762,
  centroid_lng = -99.192096,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '70ed84c1-c1e6-4246-868c-40223403a8ae'::uuid;

update simulation_personas set
  ageb_code = '090150001113A',
  centroid_lat = 19.416821,
  centroid_lng = -99.146721,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '73273333-beab-4f1c-a698-4c08c9a72ac8'::uuid;

update simulation_personas set
  ageb_code = '0901600010444',
  centroid_lat = 19.441647,
  centroid_lng = -99.204265,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '73822f8a-efba-4d88-8ab5-f3247852054e'::uuid;

update simulation_personas set
  ageb_code = '0901600010054',
  centroid_lat = 19.460188,
  centroid_lng = -99.188405,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '74d5a04a-6207-4275-8779-a40a705d85e8'::uuid;

update simulation_personas set
  ageb_code = '0901600010444',
  centroid_lat = 19.441979,
  centroid_lng = -99.203977,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '77bad0e9-9feb-42cf-b336-ae6fe288ceef'::uuid;

update simulation_personas set
  ageb_code = '0901500010875',
  centroid_lat = 19.428146,
  centroid_lng = -99.145301,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '7c0e97eb-c971-45f9-9fb1-8d51a54228bb'::uuid;

update simulation_personas set
  ageb_code = '0901500010540',
  centroid_lat = 19.444772,
  centroid_lng = -99.133008,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '7d5f1f79-a4ac-44c1-a40f-422b8c1c7b42'::uuid;

update simulation_personas set
  ageb_code = '0901600010270',
  centroid_lat = 19.450758,
  centroid_lng = -99.188024,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '8029f0e3-1af2-4586-9825-f5aeab9f50cf'::uuid;

update simulation_personas set
  ageb_code = '0901500010875',
  centroid_lat = 19.428607,
  centroid_lng = -99.145211,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '8035934b-679d-4ab2-a522-c196c57f8b8a'::uuid;

update simulation_personas set
  ageb_code = '090150001113A',
  centroid_lat = 19.416812,
  centroid_lng = -99.14641,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '817c500c-8db7-4c63-b738-026eb7251ab8'::uuid;

update simulation_personas set
  ageb_code = '0901600010069',
  centroid_lat = 19.455132,
  centroid_lng = -99.175962,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '81ee9c0d-c3fd-4351-a24b-3f9f2d9aa84b'::uuid;

update simulation_personas set
  ageb_code = '0901600010444',
  centroid_lat = 19.441832,
  centroid_lng = -99.204272,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '82facb58-7367-49ed-ab4c-4b9b6669ec6b'::uuid;

update simulation_personas set
  ageb_code = '0901600010641',
  centroid_lat = 19.434825,
  centroid_lng = -99.198673,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '876809bd-63e6-4915-a1fd-c9fd8ac9d2a2'::uuid;

update simulation_personas set
  ageb_code = '0901500011233',
  centroid_lat = 19.412442,
  centroid_lng = -99.147327,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '87c434f5-09f8-49f4-9d5d-2d8681dc54ab'::uuid;

update simulation_personas set
  ageb_code = '0901500011125',
  centroid_lat = 19.41644,
  centroid_lng = -99.151766,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '8d0e5df2-2fbf-4c9d-aa98-a084f795aa69'::uuid;

update simulation_personas set
  ageb_code = '0901600010641',
  centroid_lat = 19.434857,
  centroid_lng = -99.199067,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '8f7587cf-1d8d-4b9a-8a07-8cbc6b8906fb'::uuid;

update simulation_personas set
  ageb_code = '0901600010779',
  centroid_lat = 19.428585,
  centroid_lng = -99.1939,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '906bcd83-5d6f-40f0-83a8-e3ab1660333a'::uuid;

update simulation_personas set
  ageb_code = '0901500011394',
  centroid_lat = 19.408202,
  centroid_lng = -99.147993,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '929779b3-87ad-433d-9069-0cdd970a6a5d'::uuid;

update simulation_personas set
  ageb_code = '090150001113A',
  centroid_lat = 19.416436,
  centroid_lng = -99.146681,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '92fec117-ac14-4291-9b6b-30e809f47ce2'::uuid;

update simulation_personas set
  ageb_code = '0901500011144',
  centroid_lat = 19.416031,
  centroid_lng = -99.1414,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '94a007a4-e22f-454c-9deb-479b1ae11cd8'::uuid;

update simulation_personas set
  ageb_code = '0901500011303',
  centroid_lat = 19.412814,
  centroid_lng = -99.179639,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '94faaf43-efb6-4dde-b540-3ebcb9ff74e4'::uuid;

update simulation_personas set
  ageb_code = '0901600010054',
  centroid_lat = 19.460359,
  centroid_lng = -99.188476,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '9575568d-dc07-4ba6-8cc2-e25aa74a048d'::uuid;

update simulation_personas set
  ageb_code = '0901500011534',
  centroid_lat = 19.423388,
  centroid_lng = -99.150832,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '972012b3-e54b-4fe9-9724-ea2e348b71ce'::uuid;

update simulation_personas set
  ageb_code = '0901600010270',
  centroid_lat = 19.450844,
  centroid_lng = -99.188268,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '9af187aa-91b2-4e32-b2fd-68083e200ec4'::uuid;

update simulation_personas set
  ageb_code = '0901500010860',
  centroid_lat = 19.429777,
  centroid_lng = -99.150506,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '9d79f6f4-f32f-42af-8153-06ca98b88124'::uuid;

update simulation_personas set
  ageb_code = '0901500011002',
  centroid_lat = 19.420453,
  centroid_lng = -99.161308,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '9f656431-f6d0-4d39-9db8-96c374a0df70'::uuid;

update simulation_personas set
  ageb_code = '0901500011534',
  centroid_lat = 19.422981,
  centroid_lng = -99.151243,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'a133091f-38b2-4384-b56d-2a7d4a1451dd'::uuid;

update simulation_personas set
  ageb_code = '0901500010540',
  centroid_lat = 19.445026,
  centroid_lng = -99.132887,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'a25c113c-6383-4b9a-8966-fbff3ffcfe3b'::uuid;

update simulation_personas set
  ageb_code = '0901500011394',
  centroid_lat = 19.408351,
  centroid_lng = -99.148189,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'a26238dc-451a-45b1-b5a2-c90d94340a05'::uuid;

update simulation_personas set
  ageb_code = '0901500010875',
  centroid_lat = 19.428369,
  centroid_lng = -99.144984,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'a3e28c26-1e34-41cf-b388-8af147115550'::uuid;

update simulation_personas set
  ageb_code = '0901600010463',
  centroid_lat = 19.444068,
  centroid_lng = -99.192543,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'a3ea3c5d-40be-4ddf-9529-2d4d69a9149d'::uuid;

update simulation_personas set
  ageb_code = '0901500011144',
  centroid_lat = 19.41621,
  centroid_lng = -99.141105,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'a49c0a19-d81e-4633-b524-fe5628ee18ef'::uuid;

update simulation_personas set
  ageb_code = '0901500010343',
  centroid_lat = 19.447881,
  centroid_lng = -99.128922,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'aaa7cf1d-d691-4bd3-9db2-5c638984efcd'::uuid;

update simulation_personas set
  ageb_code = '0901500011394',
  centroid_lat = 19.408442,
  centroid_lng = -99.147788,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'abb9d106-1084-411a-a57e-bf3667bc1e65'::uuid;

update simulation_personas set
  ageb_code = '0901500010875',
  centroid_lat = 19.428489,
  centroid_lng = -99.145152,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'ad32b1c1-ce3c-4847-b05a-1b4c9b6faaa2'::uuid;

update simulation_personas set
  ageb_code = '0901600010270',
  centroid_lat = 19.451036,
  centroid_lng = -99.187872,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'b14f580a-d514-41d7-9a74-e226eade5468'::uuid;

update simulation_personas set
  ageb_code = '0901600010779',
  centroid_lat = 19.428261,
  centroid_lng = -99.194097,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'b360b50c-3d90-413f-93ff-416c5c7c5973'::uuid;

update simulation_personas set
  ageb_code = '0901600010181',
  centroid_lat = 19.449894,
  centroid_lng = -99.17929,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'b4fc7711-da7e-42b4-b706-084bc5757175'::uuid;

update simulation_personas set
  ageb_code = '0901600010637',
  centroid_lat = 19.435088,
  centroid_lng = -99.204295,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'b56e4a79-8d12-4258-8ffc-2eb54309093d'::uuid;

update simulation_personas set
  ageb_code = '0901500010860',
  centroid_lat = 19.429226,
  centroid_lng = -99.150677,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'b59309a1-2902-4911-a853-9f1b34145a17'::uuid;

update simulation_personas set
  ageb_code = '0901600010069',
  centroid_lat = 19.455357,
  centroid_lng = -99.176086,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'bb644e38-0f8a-49fd-905c-15d90bd1b91a'::uuid;

update simulation_personas set
  ageb_code = '0901500011341',
  centroid_lat = 19.409017,
  centroid_lng = -99.169963,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'bc9af880-cf99-4d26-b404-3c2700c55d01'::uuid;

update simulation_personas set
  ageb_code = '0901600011207',
  centroid_lat = 19.40078,
  centroid_lng = -99.179673,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'bdae26f2-5bda-45f9-b9b4-5c23e799e4d6'::uuid;

update simulation_personas set
  ageb_code = '0901600010783',
  centroid_lat = 19.429146,
  centroid_lng = -99.187846,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'be2359f1-7b36-44d8-91fc-57c6498e4455'::uuid;

update simulation_personas set
  ageb_code = '0901500011036',
  centroid_lat = 19.422369,
  centroid_lng = -99.146064,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'bf908645-102a-4b7a-839d-f9e8673f2007'::uuid;

update simulation_personas set
  ageb_code = '0901500011341',
  centroid_lat = 19.408672,
  centroid_lng = -99.170292,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'c1f1bf4e-5eb1-4dba-b6e7-d157da7f9f14'::uuid;

update simulation_personas set
  ageb_code = '0901500011534',
  centroid_lat = 19.423085,
  centroid_lng = -99.15114,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'c32fd288-5056-435d-a44c-0375a3e2c39c'::uuid;

update simulation_personas set
  ageb_code = '0901600010143',
  centroid_lat = 19.455075,
  centroid_lng = -99.19325,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'c3f498d1-ccda-44a4-a749-cdce42ed8621'::uuid;

update simulation_personas set
  ageb_code = '0901500010682',
  centroid_lat = 19.437973,
  centroid_lng = -99.162577,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'c57ffe4f-bba7-4e51-b30f-524ce80effd7'::uuid;

update simulation_personas set
  ageb_code = '0901500011040',
  centroid_lat = 19.422167,
  centroid_lng = -99.140181,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'ce1dc5d2-d9ec-4aad-9904-cc58d65ee108'::uuid;

update simulation_personas set
  ageb_code = '0901500010964',
  centroid_lat = 19.425371,
  centroid_lng = -99.137661,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'cf48e269-128e-42e7-b0a8-18625b9843ec'::uuid;

update simulation_personas set
  ageb_code = '0901500011356',
  centroid_lat = 19.409317,
  centroid_lng = -99.16539,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'cfa7c8e4-1550-4a92-bac9-d85fcf57e986'::uuid;

update simulation_personas set
  ageb_code = '0901600010783',
  centroid_lat = 19.428494,
  centroid_lng = -99.187847,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'd0eda7a9-92f8-401e-b665-ca1d17175451'::uuid;

update simulation_personas set
  ageb_code = '0901500010856',
  centroid_lat = 19.429113,
  centroid_lng = -99.154995,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'd106b5bd-dbd0-4224-a552-85c3154bcc12'::uuid;

update simulation_personas set
  ageb_code = '090150001113A',
  centroid_lat = 19.416764,
  centroid_lng = -99.146698,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'd1a6fa70-a084-4dc8-889c-491b9f61c107'::uuid;

update simulation_personas set
  ageb_code = '0901600010478',
  centroid_lat = 19.442819,
  centroid_lng = -99.185768,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'd1edce80-80bf-4e75-b85c-7f21abe4fdd7'::uuid;

update simulation_personas set
  ageb_code = '0901500011110',
  centroid_lat = 19.415477,
  centroid_lng = -99.156617,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'd302c956-10c9-4113-93a3-96bf40be4f40'::uuid;

update simulation_personas set
  ageb_code = '0901500011341',
  centroid_lat = 19.408818,
  centroid_lng = -99.170176,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'd545a987-786a-4053-8c73-3f240fc14b08'::uuid;

update simulation_personas set
  ageb_code = '0901500011411',
  centroid_lat = 19.40846,
  centroid_lng = -99.180255,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'd78b6369-4a42-4628-a42b-8c15ecdefd48'::uuid;

update simulation_personas set
  ageb_code = '0901600010444',
  centroid_lat = 19.442065,
  centroid_lng = -99.203832,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'd7e55280-db4b-4fdf-a1ef-8a85e48fb5a7'::uuid;

update simulation_personas set
  ageb_code = '0901500011144',
  centroid_lat = 19.416223,
  centroid_lng = -99.141002,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'da6f91d9-3585-439a-8cf2-b016e1305c95'::uuid;

update simulation_personas set
  ageb_code = '0901500011125',
  centroid_lat = 19.415948,
  centroid_lng = -99.151769,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'dcd39767-6cb3-474c-8e10-21b314844ca0'::uuid;

update simulation_personas set
  ageb_code = '0901500011089',
  centroid_lat = 19.419815,
  centroid_lng = -99.173929,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'ddaccac4-d8fd-4862-979b-bad3b27ae941'::uuid;

update simulation_personas set
  ageb_code = '0901600010181',
  centroid_lat = 19.450098,
  centroid_lng = -99.179142,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'ddd60b82-4e87-459f-af9a-9fabca372be8'::uuid;

update simulation_personas set
  ageb_code = '0901500011248',
  centroid_lat = 19.411033,
  centroid_lng = -99.142953,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'df54e86f-7a2b-4dd5-b11c-85fbb473e4bb'::uuid;

update simulation_personas set
  ageb_code = '0901600010270',
  centroid_lat = 19.450943,
  centroid_lng = -99.187764,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'e1173d15-b89b-4367-b301-43d95315178c'::uuid;

update simulation_personas set
  ageb_code = '0901600010444',
  centroid_lat = 19.442175,
  centroid_lng = -99.203954,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'e2844454-fb14-4cae-9a43-570fece44d1e'::uuid;

update simulation_personas set
  ageb_code = '0901600010497',
  centroid_lat = 19.441667,
  centroid_lng = -99.173546,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'ead2bebf-1b2c-41be-9586-60d26fbb96c9'::uuid;

update simulation_personas set
  ageb_code = '0901500011394',
  centroid_lat = 19.408461,
  centroid_lng = -99.147609,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'ecf68464-1802-49b4-9816-89198f4ea397'::uuid;

update simulation_personas set
  ageb_code = '0901600010139',
  centroid_lat = 19.457295,
  centroid_lng = -99.195004,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'efdb2bdc-435e-4104-b4a2-9f0c2b83f724'::uuid;

update simulation_personas set
  ageb_code = '0901500010358',
  centroid_lat = 19.447372,
  centroid_lng = -99.126527,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'f0ce23ea-f580-4546-8ba3-c8f14ca345d0'::uuid;

update simulation_personas set
  ageb_code = '090150001113A',
  centroid_lat = 19.416833,
  centroid_lng = -99.146879,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'f0dcb02b-5250-459a-969d-b244ecb1962d'::uuid;

update simulation_personas set
  ageb_code = '0901600010656',
  centroid_lat = 19.434976,
  centroid_lng = -99.193241,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'f1163ba3-cc8b-423b-a5ba-b6e00fa316a7'::uuid;

update simulation_personas set
  ageb_code = '0901500011248',
  centroid_lat = 19.410357,
  centroid_lng = -99.142744,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'f16417af-27a1-48c0-bb1a-35a1075f5227'::uuid;

update simulation_personas set
  ageb_code = '0901500011144',
  centroid_lat = 19.415992,
  centroid_lng = -99.141038,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'f242cb21-158b-4fba-8e07-ae247aa3441b'::uuid;

update simulation_personas set
  ageb_code = '0901500011106',
  centroid_lat = 19.416553,
  centroid_lng = -99.161701,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'f41f07af-0737-4584-bb17-c64536accae9'::uuid;

update simulation_personas set
  ageb_code = '0901500010339',
  centroid_lat = 19.450285,
  centroid_lng = -99.131665,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'f570c4d7-81de-4325-b004-70a2037d6ad2'::uuid;

update simulation_personas set
  ageb_code = '0901500011248',
  centroid_lat = 19.410884,
  centroid_lng = -99.142905,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'f9635958-70d8-4d8e-b20c-3d6196af8588'::uuid;

update simulation_personas set
  ageb_code = '0901500011125',
  centroid_lat = 19.416349,
  centroid_lng = -99.151659,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'fa58a4ee-f445-4fe2-80bc-32b14147967c'::uuid;

update simulation_personas set
  ageb_code = '0901600010444',
  centroid_lat = 19.442087,
  centroid_lng = -99.204104,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'fdb09081-d302-45f6-958a-83f97e1248ad'::uuid;

update simulation_personas set
  ageb_code = '0901500011394',
  centroid_lat = 19.408305,
  centroid_lng = -99.148024,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'ff258f97-955a-4af4-8369-27f52a4e1b52'::uuid;

commit;

-- Verification (read-only; run after the transaction)
select
  ageb_assignment_method,
  count(*) as n
from simulation_personas
where version = 'cdmx-v1'
group by ageb_assignment_method
order by ageb_assignment_method nulls first;

select
  count(*) filter (where ageb_code is null) as null_ageb_code,
  count(*) filter (where ageb_code is not null) as assigned_ageb_code,
  count(*) as total
from simulation_personas
where version = 'cdmx-v1';
