-- 268_persona_ageb_assign.sql
-- Task 4a.2 — owner-run UPDATE for simulation_personas AGEB fields.
-- Generated by scripts/geo/assign-persona-agebs.ts
-- run_id: 1ace1e55-e37a-4f0f-9c2d-2c31a13a1291
--
-- Touches ONLY: ageb_code, centroid_lat, centroid_lng, ageb_assignment_method
-- Requires migration 268_persona_ageb_assignment_method.sql first.
-- Idempotent: re-running sets the same values for the same persona ids.
-- Never touches prediction_markets / market_votes / real vote tables.

begin;

update simulation_personas set
  ageb_code = '0901600010054',
  centroid_lat = 19.461343,
  centroid_lng = -99.189341,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '010cbf28-86b4-488c-a90b-175b9117a611'::uuid;

update simulation_personas set
  ageb_code = '0901500011303',
  centroid_lat = 19.413339,
  centroid_lng = -99.179365,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '02b51dd0-b4d0-4428-96ea-5bfebd6ba4dd'::uuid;

update simulation_personas set
  ageb_code = '0901500011110',
  centroid_lat = 19.414175,
  centroid_lng = -99.156444,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '03bf61bb-febc-47d9-a16c-115bdc948f60'::uuid;

update simulation_personas set
  ageb_code = '0901600010158',
  centroid_lat = 19.456891,
  centroid_lng = -99.187795,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '03c2eecc-d1fd-4560-ada6-51d049139fe9'::uuid;

update simulation_personas set
  ageb_code = '090150001113A',
  centroid_lat = 19.416979,
  centroid_lng = -99.146601,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '0822e27b-c7a2-43f3-9f0c-e16849424cce'::uuid;

update simulation_personas set
  ageb_code = '0901500011549',
  centroid_lat = 19.420837,
  centroid_lng = -99.152445,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '08df5b3d-aaf8-43ba-89f8-1f6847e8d59d'::uuid;

update simulation_personas set
  ageb_code = '0901500011303',
  centroid_lat = 19.413052,
  centroid_lng = -99.179255,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '0b9bc6ee-cb99-4882-bfbe-27674534766c'::uuid;

update simulation_personas set
  ageb_code = '0901500010466',
  centroid_lat = 19.452651,
  centroid_lng = -99.160525,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '0caed288-d975-41b0-a097-7c58582eaa41'::uuid;

update simulation_personas set
  ageb_code = '0901600010158',
  centroid_lat = 19.456353,
  centroid_lng = -99.188002,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '0f787c0e-1333-40bb-8aa0-808d3b04c927'::uuid;

update simulation_personas set
  ageb_code = '0901500010540',
  centroid_lat = 19.445117,
  centroid_lng = -99.132576,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '0fe51b43-25a6-4b85-9ccb-938be299c9c9'::uuid;

update simulation_personas set
  ageb_code = '0901500010593',
  centroid_lat = 19.444664,
  centroid_lng = -99.161937,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '104f774f-69be-4b5a-a7fd-442a543a2bc8'::uuid;

update simulation_personas set
  ageb_code = '0901500011036',
  centroid_lat = 19.421092,
  centroid_lng = -99.146076,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '145a052c-1b94-44a4-bf52-e08b0b77eae1'::uuid;

update simulation_personas set
  ageb_code = '0901500010998',
  centroid_lat = 19.420748,
  centroid_lng = -99.167299,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '14850982-416b-4160-8f13-34e9ddd96fd7'::uuid;

update simulation_personas set
  ageb_code = '0901600010779',
  centroid_lat = 19.427845,
  centroid_lng = -99.193736,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '169d3d63-e2d7-4d87-a981-f4754c8abe45'::uuid;

update simulation_personas set
  ageb_code = '0901600010143',
  centroid_lat = 19.454931,
  centroid_lng = -99.191813,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '17e0489e-ac16-40c4-b77b-11eddebef453'::uuid;

update simulation_personas set
  ageb_code = '0901600010143',
  centroid_lat = 19.455267,
  centroid_lng = -99.191547,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '18515a15-d2c0-4535-91ff-928231786a31'::uuid;

update simulation_personas set
  ageb_code = '0901600010891',
  centroid_lat = 19.415433,
  centroid_lng = -99.182166,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '1976e109-0034-4567-a785-c717b6fdf855'::uuid;

update simulation_personas set
  ageb_code = '0901600010637',
  centroid_lat = 19.434727,
  centroid_lng = -99.204335,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '1af3c2e5-5aeb-464e-87fe-7da422d26db6'::uuid;

update simulation_personas set
  ageb_code = '0901600010158',
  centroid_lat = 19.456478,
  centroid_lng = -99.187917,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '1b6ca2f6-0128-4b47-8aa4-6580665062aa'::uuid;

update simulation_personas set
  ageb_code = '0901500011229',
  centroid_lat = 19.410646,
  centroid_lng = -99.152888,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '1c106c1a-1595-4816-a8a6-e5ad63a8fb8c'::uuid;

update simulation_personas set
  ageb_code = '0901500011233',
  centroid_lat = 19.412367,
  centroid_lng = -99.147233,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '1f8a5ee9-c587-40e6-806d-28bf65445993'::uuid;

update simulation_personas set
  ageb_code = '0901500011093',
  centroid_lat = 19.418318,
  centroid_lng = -99.167661,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '1fa0e082-9b35-4e65-9256-28c5cb34db7d'::uuid;

update simulation_personas set
  ageb_code = '0901500011483',
  centroid_lat = 19.405528,
  centroid_lng = -99.147759,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '20acdd2c-615a-46c7-9095-740875d12c70'::uuid;

update simulation_personas set
  ageb_code = '0901500011093',
  centroid_lat = 19.417831,
  centroid_lng = -99.167697,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '22dda38a-99a8-44a6-b2a2-507c106b6505'::uuid;

update simulation_personas set
  ageb_code = '0901600010497',
  centroid_lat = 19.441488,
  centroid_lng = -99.173665,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '277ca9cd-0409-4f99-a913-c8d0316471fd'::uuid;

update simulation_personas set
  ageb_code = '0901500011125',
  centroid_lat = 19.41593,
  centroid_lng = -99.152316,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '27d99059-6823-4343-ab7d-f5056d39cd39'::uuid;

update simulation_personas set
  ageb_code = '0901500010358',
  centroid_lat = 19.44763,
  centroid_lng = -99.126863,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '2ca719f9-5f91-425c-ab3b-938c1fe7544e'::uuid;

update simulation_personas set
  ageb_code = '0901500011017',
  centroid_lat = 19.421944,
  centroid_lng = -99.15666,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '2ccc121f-f298-4dc2-b5d6-8b2d24dad280'::uuid;

update simulation_personas set
  ageb_code = '0901500011110',
  centroid_lat = 19.413504,
  centroid_lng = -99.156756,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '2dad7ecb-4c4e-47e8-92e9-d4574b9791a6'::uuid;

update simulation_personas set
  ageb_code = '0901600010622',
  centroid_lat = 19.436303,
  centroid_lng = -99.210051,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '2e5348c2-380d-4425-8f92-0a7606634096'::uuid;

update simulation_personas set
  ageb_code = '0901500011318',
  centroid_lat = 19.410019,
  centroid_lng = -99.177161,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '2ff926fd-6197-49c4-a470-a5fb1ef59366'::uuid;

update simulation_personas set
  ageb_code = '0901500010470',
  centroid_lat = 19.4534,
  centroid_lng = -99.156347,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '352cbf6b-2c15-46f7-92dd-3eea10ce3c44'::uuid;

update simulation_personas set
  ageb_code = '0901500011178',
  centroid_lat = 19.416925,
  centroid_lng = -99.177041,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '35e434b8-ea50-4209-b131-665e00fa6d24'::uuid;

update simulation_personas set
  ageb_code = '0901600010675',
  centroid_lat = 19.433936,
  centroid_lng = -99.186185,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '360a5eae-8737-45b6-8ee1-d3fbf47a1aa7'::uuid;

update simulation_personas set
  ageb_code = '0901500011110',
  centroid_lat = 19.41408,
  centroid_lng = -99.156639,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '3783d8e5-116d-437a-85fb-bf728b78a469'::uuid;

update simulation_personas set
  ageb_code = '0901500011233',
  centroid_lat = 19.412708,
  centroid_lng = -99.147024,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '3a1878ed-655b-442a-93f8-aa9d98939351'::uuid;

update simulation_personas set
  ageb_code = '090150001113A',
  centroid_lat = 19.416991,
  centroid_lng = -99.14648,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '3c1f1ade-663f-4aff-a0bf-a6c0aa707622'::uuid;

update simulation_personas set
  ageb_code = '0901500011110',
  centroid_lat = 19.413493,
  centroid_lng = -99.156332,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '3c71d83b-6d44-483b-809d-ca063969be26'::uuid;

update simulation_personas set
  ageb_code = '0901500011017',
  centroid_lat = 19.421882,
  centroid_lng = -99.156925,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '3e080c61-269c-4e90-a128-28329b277fea'::uuid;

update simulation_personas set
  ageb_code = '090150001113A',
  centroid_lat = 19.416972,
  centroid_lng = -99.146441,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '40716ff6-ae2f-45df-9d5b-0f4f6a39a7ac'::uuid;

update simulation_personas set
  ageb_code = '090160001068A',
  centroid_lat = 19.432595,
  centroid_lng = -99.182772,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '408e4973-8d61-4fb3-8e58-49b70c0020ab'::uuid;

update simulation_personas set
  ageb_code = '0901600010745',
  centroid_lat = 19.43038,
  centroid_lng = -99.202546,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '432aef30-68b4-4eff-868b-8b4d4863245a'::uuid;

update simulation_personas set
  ageb_code = '0901500011017',
  centroid_lat = 19.421723,
  centroid_lng = -99.156569,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '43e5eeae-b0e3-4b8c-bd0a-2106c7c94ad8'::uuid;

update simulation_personas set
  ageb_code = '0901500011214',
  centroid_lat = 19.413471,
  centroid_lng = -99.162305,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '4473e59d-6b76-4b6e-8329-a82bd8215e4b'::uuid;

update simulation_personas set
  ageb_code = '0901500011017',
  centroid_lat = 19.421955,
  centroid_lng = -99.156537,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '46b48204-b678-4133-8ea2-533c17d33e5e'::uuid;

update simulation_personas set
  ageb_code = '090150001113A',
  centroid_lat = 19.416639,
  centroid_lng = -99.146748,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '476a73ac-9fbf-4664-9d95-0492309d5b33'::uuid;

update simulation_personas set
  ageb_code = '0901500011036',
  centroid_lat = 19.421135,
  centroid_lng = -99.146224,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '4924766a-b172-46c7-ae39-ce1a0a195275'::uuid;

update simulation_personas set
  ageb_code = '0901600010054',
  centroid_lat = 19.461263,
  centroid_lng = -99.189376,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '495eab1e-30ba-45b5-9765-e2c0930eeb2f'::uuid;

update simulation_personas set
  ageb_code = '0901500011110',
  centroid_lat = 19.413793,
  centroid_lng = -99.156888,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '49f49d03-7fd9-4046-9850-5ba8bce7f36f'::uuid;

update simulation_personas set
  ageb_code = '0901500010466',
  centroid_lat = 19.452257,
  centroid_lng = -99.16068,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '4b76e86b-8f52-4e19-a84f-e1313aec69c8'::uuid;

update simulation_personas set
  ageb_code = '0901500011197',
  centroid_lat = 19.414711,
  centroid_lng = -99.171584,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '4d7c095a-97ce-4879-8ffd-f15788e9e4c4'::uuid;

update simulation_personas set
  ageb_code = '0901500011394',
  centroid_lat = 19.407943,
  centroid_lng = -99.147902,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '5032c35c-2f90-4799-9842-195d2882782b'::uuid;

update simulation_personas set
  ageb_code = '0901600010783',
  centroid_lat = 19.428524,
  centroid_lng = -99.188226,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '5064a852-d2af-4519-9f33-db92dbc66ba2'::uuid;

update simulation_personas set
  ageb_code = '0901500010343',
  centroid_lat = 19.449018,
  centroid_lng = -99.128705,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '51ecd97f-b4a4-4b5a-8cdd-3575cae5620a'::uuid;

update simulation_personas set
  ageb_code = '0901500011110',
  centroid_lat = 19.414184,
  centroid_lng = -99.156532,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '52755f81-f930-475b-a94f-ebadeb667fd5'::uuid;

update simulation_personas set
  ageb_code = '0901500011233',
  centroid_lat = 19.412658,
  centroid_lng = -99.147119,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '52c4fdc2-cc27-4c9c-a805-c628f9ff1aa9'::uuid;

update simulation_personas set
  ageb_code = '0901500011233',
  centroid_lat = 19.412726,
  centroid_lng = -99.147484,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '54b3d3ce-455a-4af2-872f-85e2069b0737'::uuid;

update simulation_personas set
  ageb_code = '0901600010656',
  centroid_lat = 19.43521,
  centroid_lng = -99.193267,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '55284a8a-bfc2-4d24-8010-5a54a1e664f1'::uuid;

update simulation_personas set
  ageb_code = '0901500011394',
  centroid_lat = 19.407972,
  centroid_lng = -99.14789,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '55857cd6-17ea-4867-b904-85f8435696ab'::uuid;

update simulation_personas set
  ageb_code = '0901500011233',
  centroid_lat = 19.412519,
  centroid_lng = -99.147173,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '574a6e98-e3a0-4002-82dd-b28634a7e81e'::uuid;

update simulation_personas set
  ageb_code = '0901600010054',
  centroid_lat = 19.457147,
  centroid_lng = -99.179691,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '5cbc7e57-1b88-4e13-992b-f96981593218'::uuid;

update simulation_personas set
  ageb_code = '0901500011178',
  centroid_lat = 19.416927,
  centroid_lng = -99.17748,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '5f86fb1d-f622-442c-a4e8-85ab80586f06'::uuid;

update simulation_personas set
  ageb_code = '0901500011125',
  centroid_lat = 19.41642,
  centroid_lng = -99.151715,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '6315b4a3-b386-4f11-a554-6178d66f33b2'::uuid;

update simulation_personas set
  ageb_code = '0901500010555',
  centroid_lat = 19.447494,
  centroid_lng = -99.16132,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '64aeed2c-98fa-470d-8394-ae2142809080'::uuid;

update simulation_personas set
  ageb_code = '0901500010343',
  centroid_lat = 19.449342,
  centroid_lng = -99.128438,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '65eb68f2-5627-4ae4-90db-a53e661e71d4'::uuid;

update simulation_personas set
  ageb_code = '0901500010466',
  centroid_lat = 19.452279,
  centroid_lng = -99.160314,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '6898d5c2-84fa-4029-99b0-e16b1a9c78f3'::uuid;

update simulation_personas set
  ageb_code = '0901500011017',
  centroid_lat = 19.421812,
  centroid_lng = -99.156945,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '6c5bda1f-eca2-48a9-8db7-7dbbecb40c1a'::uuid;

update simulation_personas set
  ageb_code = '0901600010158',
  centroid_lat = 19.456932,
  centroid_lng = -99.188406,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '6de63df0-7520-4f28-8645-876af8fa85dc'::uuid;

update simulation_personas set
  ageb_code = '0901500011411',
  centroid_lat = 19.409062,
  centroid_lng = -99.180384,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '6efef3e1-8df5-44cd-b239-e3472a0ad726'::uuid;

update simulation_personas set
  ageb_code = '0901600010459',
  centroid_lat = 19.444667,
  centroid_lng = -99.199207,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '70ed84c1-c1e6-4246-868c-40223403a8ae'::uuid;

update simulation_personas set
  ageb_code = '090150001113A',
  centroid_lat = 19.416936,
  centroid_lng = -99.146714,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '73273333-beab-4f1c-a698-4c08c9a72ac8'::uuid;

update simulation_personas set
  ageb_code = '0901600010622',
  centroid_lat = 19.435863,
  centroid_lng = -99.210139,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '73822f8a-efba-4d88-8ab5-f3247852054e'::uuid;

update simulation_personas set
  ageb_code = '0901600010054',
  centroid_lat = 19.457078,
  centroid_lng = -99.179588,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '74d5a04a-6207-4275-8779-a40a705d85e8'::uuid;

update simulation_personas set
  ageb_code = '0901600010444',
  centroid_lat = 19.442522,
  centroid_lng = -99.202558,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '77bad0e9-9feb-42cf-b336-ae6fe288ceef'::uuid;

update simulation_personas set
  ageb_code = '0901500011036',
  centroid_lat = 19.420496,
  centroid_lng = -99.146001,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '7c0e97eb-c971-45f9-9fb1-8d51a54228bb'::uuid;

update simulation_personas set
  ageb_code = '0901500010540',
  centroid_lat = 19.445453,
  centroid_lng = -99.132907,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '7d5f1f79-a4ac-44c1-a40f-422b8c1c7b42'::uuid;

update simulation_personas set
  ageb_code = '0901600010270',
  centroid_lat = 19.453214,
  centroid_lng = -99.188222,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '8029f0e3-1af2-4586-9825-f5aeab9f50cf'::uuid;

update simulation_personas set
  ageb_code = '0901500011036',
  centroid_lat = 19.420957,
  centroid_lng = -99.145911,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '8035934b-679d-4ab2-a522-c196c57f8b8a'::uuid;

update simulation_personas set
  ageb_code = '090150001113A',
  centroid_lat = 19.416927,
  centroid_lng = -99.146403,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '817c500c-8db7-4c63-b738-026eb7251ab8'::uuid;

update simulation_personas set
  ageb_code = '0901600010069',
  centroid_lat = 19.455947,
  centroid_lng = -99.176858,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '81ee9c0d-c3fd-4351-a24b-3f9f2d9aa84b'::uuid;

update simulation_personas set
  ageb_code = '0901600010444',
  centroid_lat = 19.442375,
  centroid_lng = -99.202853,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '82facb58-7367-49ed-ab4c-4b9b6669ec6b'::uuid;

update simulation_personas set
  ageb_code = '0901600010660',
  centroid_lat = 19.434075,
  centroid_lng = -99.189051,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '876809bd-63e6-4915-a1fd-c9fd8ac9d2a2'::uuid;

update simulation_personas set
  ageb_code = '0901500011394',
  centroid_lat = 19.408483,
  centroid_lng = -99.147937,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '87c434f5-09f8-49f4-9d5d-2d8681dc54ab'::uuid;

update simulation_personas set
  ageb_code = '0901500011093',
  centroid_lat = 19.418355,
  centroid_lng = -99.167434,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '8d0e5df2-2fbf-4c9d-aa98-a084f795aa69'::uuid;

update simulation_personas set
  ageb_code = '0901600010660',
  centroid_lat = 19.434107,
  centroid_lng = -99.189445,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '8f7587cf-1d8d-4b9a-8a07-8cbc6b8906fb'::uuid;

update simulation_personas set
  ageb_code = '0901600010783',
  centroid_lat = 19.4286,
  centroid_lng = -99.188385,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '906bcd83-5d6f-40f0-83a8-e3ab1660333a'::uuid;

update simulation_personas set
  ageb_code = '0901500011549',
  centroid_lat = 19.420729,
  centroid_lng = -99.152278,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '929779b3-87ad-433d-9069-0cdd970a6a5d'::uuid;

update simulation_personas set
  ageb_code = '090150001113A',
  centroid_lat = 19.416551,
  centroid_lng = -99.146674,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '92fec117-ac14-4291-9b6b-30e809f47ce2'::uuid;

update simulation_personas set
  ageb_code = '0901500011233',
  centroid_lat = 19.412516,
  centroid_lng = -99.147432,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '94a007a4-e22f-454c-9deb-479b1ae11cd8'::uuid;

update simulation_personas set
  ageb_code = '0901500011318',
  centroid_lat = 19.410169,
  centroid_lng = -99.177343,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '94faaf43-efb6-4dde-b540-3ebcb9ff74e4'::uuid;

update simulation_personas set
  ageb_code = '0901600010054',
  centroid_lat = 19.457249,
  centroid_lng = -99.179659,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '9575568d-dc07-4ba6-8cc2-e25aa74a048d'::uuid;

update simulation_personas set
  ageb_code = '0901500011549',
  centroid_lat = 19.421055,
  centroid_lng = -99.151967,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '972012b3-e54b-4fe9-9724-ea2e348b71ce'::uuid;

update simulation_personas set
  ageb_code = '0901600010270',
  centroid_lat = 19.4533,
  centroid_lng = -99.188466,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '9af187aa-91b2-4e32-b2fd-68083e200ec4'::uuid;

update simulation_personas set
  ageb_code = '0901500011036',
  centroid_lat = 19.421127,
  centroid_lng = -99.146096,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '9d79f6f4-f32f-42af-8153-06ca98b88124'::uuid;

update simulation_personas set
  ageb_code = '0901500011002',
  centroid_lat = 19.420438,
  centroid_lng = -99.161312,
  ageb_assignment_method = 'colonia_census_weighted'
where id = '9f656431-f6d0-4d39-9db8-96c374a0df70'::uuid;

update simulation_personas set
  ageb_code = '0901500011549',
  centroid_lat = 19.420648,
  centroid_lng = -99.152378,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'a133091f-38b2-4384-b56d-2a7d4a1451dd'::uuid;

update simulation_personas set
  ageb_code = '0901500010536',
  centroid_lat = 19.446181,
  centroid_lng = -99.136153,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'a25c113c-6383-4b9a-8966-fbff3ffcfe3b'::uuid;

update simulation_personas set
  ageb_code = '0901500011534',
  centroid_lat = 19.422746,
  centroid_lng = -99.151398,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'a26238dc-451a-45b1-b5a2-c90d94340a05'::uuid;

update simulation_personas set
  ageb_code = '0901500011036',
  centroid_lat = 19.420719,
  centroid_lng = -99.145684,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'a3e28c26-1e34-41cf-b388-8af147115550'::uuid;

update simulation_personas set
  ageb_code = '0901600010463',
  centroid_lat = 19.445156,
  centroid_lng = -99.198263,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'a3ea3c5d-40be-4ddf-9529-2d4d69a9149d'::uuid;

update simulation_personas set
  ageb_code = '0901500011233',
  centroid_lat = 19.412695,
  centroid_lng = -99.147137,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'a49c0a19-d81e-4633-b524-fe5628ee18ef'::uuid;

update simulation_personas set
  ageb_code = '0901500010343',
  centroid_lat = 19.449041,
  centroid_lng = -99.128701,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'aaa7cf1d-d691-4bd3-9db2-5c638984efcd'::uuid;

update simulation_personas set
  ageb_code = '0901500011549',
  centroid_lat = 19.420969,
  centroid_lng = -99.152073,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'abb9d106-1084-411a-a57e-bf3667bc1e65'::uuid;

update simulation_personas set
  ageb_code = '0901500011036',
  centroid_lat = 19.420839,
  centroid_lng = -99.145852,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'ad32b1c1-ce3c-4847-b05a-1b4c9b6faaa2'::uuid;

update simulation_personas set
  ageb_code = '0901600010162',
  centroid_lat = 19.455606,
  centroid_lng = -99.185774,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'b14f580a-d514-41d7-9a74-e226eade5468'::uuid;

update simulation_personas set
  ageb_code = '0901600010783',
  centroid_lat = 19.428276,
  centroid_lng = -99.188582,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'b360b50c-3d90-413f-93ff-416c5c7c5973'::uuid;

update simulation_personas set
  ageb_code = '0901600010285',
  centroid_lat = 19.444464,
  centroid_lng = -99.176524,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'b4fc7711-da7e-42b4-b706-084bc5757175'::uuid;

update simulation_personas set
  ageb_code = '0901600010660',
  centroid_lat = 19.434688,
  centroid_lng = -99.189013,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'b56e4a79-8d12-4258-8ffc-2eb54309093d'::uuid;

update simulation_personas set
  ageb_code = '0901500010875',
  centroid_lat = 19.425767,
  centroid_lng = -99.145133,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'b59309a1-2902-4911-a853-9f1b34145a17'::uuid;

update simulation_personas set
  ageb_code = '0901600010069',
  centroid_lat = 19.456172,
  centroid_lng = -99.176982,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'bb644e38-0f8a-49fd-905c-15d90bd1b91a'::uuid;

update simulation_personas set
  ageb_code = '0901500011110',
  centroid_lat = 19.413998,
  centroid_lng = -99.156575,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'bc9af880-cf99-4d26-b404-3c2700c55d01'::uuid;

update simulation_personas set
  ageb_code = '0901600011207',
  centroid_lat = 19.400817,
  centroid_lng = -99.179641,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'bdae26f2-5bda-45f9-b9b4-5c23e799e4d6'::uuid;

update simulation_personas set
  ageb_code = '0901600010783',
  centroid_lat = 19.428921,
  centroid_lng = -99.188131,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'be2359f1-7b36-44d8-91fc-57c6498e4455'::uuid;

update simulation_personas set
  ageb_code = '0901500011125',
  centroid_lat = 19.416484,
  centroid_lng = -99.152322,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'bf908645-102a-4b7a-839d-f9e8673f2007'::uuid;

update simulation_personas set
  ageb_code = '0901500011110',
  centroid_lat = 19.413653,
  centroid_lng = -99.156904,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'c1f1bf4e-5eb1-4dba-b6e7-d157da7f9f14'::uuid;

update simulation_personas set
  ageb_code = '0901500011549',
  centroid_lat = 19.420752,
  centroid_lng = -99.152275,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'c32fd288-5056-435d-a44c-0375a3e2c39c'::uuid;

update simulation_personas set
  ageb_code = '0901600010158',
  centroid_lat = 19.45645,
  centroid_lng = -99.188318,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'c3f498d1-ccda-44a4-a749-cdce42ed8621'::uuid;

update simulation_personas set
  ageb_code = '0901500010682',
  centroid_lat = 19.436361,
  centroid_lng = -99.163,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'c57ffe4f-bba7-4e51-b30f-524ce80effd7'::uuid;

update simulation_personas set
  ageb_code = '0901500011125',
  centroid_lat = 19.416532,
  centroid_lng = -99.151669,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'ce1dc5d2-d9ec-4aad-9904-cc58d65ee108'::uuid;

update simulation_personas set
  ageb_code = '0901500011036',
  centroid_lat = 19.421061,
  centroid_lng = -99.145821,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'cf48e269-128e-42e7-b0a8-18625b9843ec'::uuid;

update simulation_personas set
  ageb_code = '0901500011110',
  centroid_lat = 19.414078,
  centroid_lng = -99.156342,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'cfa7c8e4-1550-4a92-bac9-d85fcf57e986'::uuid;

update simulation_personas set
  ageb_code = '0901600010783',
  centroid_lat = 19.428269,
  centroid_lng = -99.188132,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'd0eda7a9-92f8-401e-b665-ca1d17175451'::uuid;

update simulation_personas set
  ageb_code = '0901500010998',
  centroid_lat = 19.420778,
  centroid_lng = -99.167667,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'd106b5bd-dbd0-4224-a552-85c3154bcc12'::uuid;

update simulation_personas set
  ageb_code = '090150001113A',
  centroid_lat = 19.416879,
  centroid_lng = -99.146691,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'd1a6fa70-a084-4dc8-889c-491b9f61c107'::uuid;

update simulation_personas set
  ageb_code = '090160001029A',
  centroid_lat = 19.446904,
  centroid_lng = -99.171701,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'd1edce80-80bf-4e75-b85c-7f21abe4fdd7'::uuid;

update simulation_personas set
  ageb_code = '0901500011089',
  centroid_lat = 19.419828,
  centroid_lng = -99.173587,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'd302c956-10c9-4113-93a3-96bf40be4f40'::uuid;

update simulation_personas set
  ageb_code = '0901500011110',
  centroid_lat = 19.413799,
  centroid_lng = -99.156788,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'd545a987-786a-4053-8c73-3f240fc14b08'::uuid;

update simulation_personas set
  ageb_code = '0901500011322',
  centroid_lat = 19.413835,
  centroid_lng = -99.174827,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'd78b6369-4a42-4628-a42b-8c15ecdefd48'::uuid;

update simulation_personas set
  ageb_code = '0901600010637',
  centroid_lat = 19.43486,
  centroid_lng = -99.20435,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'd7e55280-db4b-4fdf-a1ef-8a85e48fb5a7'::uuid;

update simulation_personas set
  ageb_code = '0901500011233',
  centroid_lat = 19.412708,
  centroid_lng = -99.147034,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'da6f91d9-3585-439a-8cf2-b016e1305c95'::uuid;

update simulation_personas set
  ageb_code = '0901500011089',
  centroid_lat = 19.419609,
  centroid_lng = -99.173539,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'dcd39767-6cb3-474c-8e10-21b314844ca0'::uuid;

update simulation_personas set
  ageb_code = '0901500011178',
  centroid_lat = 19.41685,
  centroid_lng = -99.17723,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'ddaccac4-d8fd-4862-979b-bad3b27ae941'::uuid;

update simulation_personas set
  ageb_code = '0901600010181',
  centroid_lat = 19.452971,
  centroid_lng = -99.177764,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'ddd60b82-4e87-459f-af9a-9fabca372be8'::uuid;

update simulation_personas set
  ageb_code = '0901500011394',
  centroid_lat = 19.408524,
  centroid_lng = -99.147993,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'df54e86f-7a2b-4dd5-b11c-85fbb473e4bb'::uuid;

update simulation_personas set
  ageb_code = '0901600010270',
  centroid_lat = 19.453399,
  centroid_lng = -99.187962,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'e1173d15-b89b-4367-b301-43d95315178c'::uuid;

update simulation_personas set
  ageb_code = '0901600010637',
  centroid_lat = 19.43497,
  centroid_lng = -99.204472,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'e2844454-fb14-4cae-9a43-570fece44d1e'::uuid;

update simulation_personas set
  ageb_code = '0901600010482',
  centroid_lat = 19.440348,
  centroid_lng = -99.180172,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'ead2bebf-1b2c-41be-9586-60d26fbb96c9'::uuid;

update simulation_personas set
  ageb_code = '0901500011534',
  centroid_lat = 19.422856,
  centroid_lng = -99.150818,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'ecf68464-1802-49b4-9816-89198f4ea397'::uuid;

update simulation_personas set
  ageb_code = '0901600010143',
  centroid_lat = 19.455264,
  centroid_lng = -99.191847,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'efdb2bdc-435e-4104-b4a2-9f0c2b83f724'::uuid;

update simulation_personas set
  ageb_code = '0901500010358',
  centroid_lat = 19.447369,
  centroid_lng = -99.126509,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'f0ce23ea-f580-4546-8ba3-c8f14ca345d0'::uuid;

update simulation_personas set
  ageb_code = '090150001113A',
  centroid_lat = 19.416948,
  centroid_lng = -99.146872,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'f0dcb02b-5250-459a-969d-b244ecb1962d'::uuid;

update simulation_personas set
  ageb_code = '0901600010660',
  centroid_lat = 19.434176,
  centroid_lng = -99.188959,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'f1163ba3-cc8b-423b-a5ba-b6e00fa316a7'::uuid;

update simulation_personas set
  ageb_code = '0901500011394',
  centroid_lat = 19.407848,
  centroid_lng = -99.147784,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'f16417af-27a1-48c0-bb1a-35a1075f5227'::uuid;

update simulation_personas set
  ageb_code = '0901500011233',
  centroid_lat = 19.412477,
  centroid_lng = -99.14707,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'f242cb21-158b-4fba-8e07-ae247aa3441b'::uuid;

update simulation_personas set
  ageb_code = '0901500011017',
  centroid_lat = 19.421928,
  centroid_lng = -99.156331,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'f41f07af-0737-4584-bb17-c64536accae9'::uuid;

update simulation_personas set
  ageb_code = '0901500010343',
  centroid_lat = 19.449065,
  centroid_lng = -99.128814,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'f570c4d7-81de-4325-b004-70a2037d6ad2'::uuid;

update simulation_personas set
  ageb_code = '0901500011394',
  centroid_lat = 19.408375,
  centroid_lng = -99.147945,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'f9635958-70d8-4d8e-b20c-3d6196af8588'::uuid;

update simulation_personas set
  ageb_code = '090150001113A',
  centroid_lat = 19.416934,
  centroid_lng = -99.146222,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'fa58a4ee-f445-4fe2-80bc-32b14147967c'::uuid;

update simulation_personas set
  ageb_code = '0901600010444',
  centroid_lat = 19.44263,
  centroid_lng = -99.202685,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'fdb09081-d302-45f6-958a-83f97e1248ad'::uuid;

update simulation_personas set
  ageb_code = '0901500011549',
  centroid_lat = 19.420832,
  centroid_lng = -99.152309,
  ageb_assignment_method = 'colonia_census_weighted'
where id = 'ff258f97-955a-4af4-8369-27f52a4e1b52'::uuid;

commit;

-- Verification (read-only; run after the transaction)
select
  ageb_assignment_method,
  count(*) as n
from simulation_personas
where version = 'cdmx-v1'
group by ageb_assignment_method
order by ageb_assignment_method nulls first;

select
  count(*) filter (where ageb_code is null) as null_ageb_code,
  count(*) filter (where ageb_code is not null) as assigned_ageb_code,
  count(*) as total
from simulation_personas
where version = 'cdmx-v1';
